### ISSUE TITLE
Complete First Release Version

### ISSUE THREAD

**Issue by Ragdata** [Ragdata/bash-bits#1]
Requires the following modules / sub-modules:

- [ ] Appearance module
- [ ] Dotfiles Module
  - [ ] Alias Sub-Module
  - [ ] Completion Sub-Module
  - [ ] Profile Sub-Module
  - [ ] Prompt Sub-Module
- [ ] Functions Module
  - [ ] Filesystem Sub-Module
  - [ ] Helpers Sub-Module
  - [ ] History Sub-Module
  - [ ] Logging Sub-Module
  - [ ] PreExec Sub-Module
  - [ ] Search Sub-Module
  - [ ] Utilities Sub-Module

**Comment by Ragdata** [comment]
BB-Common Module just released as prerelease version 0.1.1
